apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-demo-app
  labels:
    app: k8s-demo-app
   
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: k8s-demo-app
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
